### PR TITLE
Add TS definitions form DefinitelyTyped

### PR DESCRIPTION
**Pull request by nikeee**
This PR adds the type definitions from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/easy-table/index.d.ts

As soon as there is a released package version which contains these definitions, I have to file a PR in DefinitelyTyped to remove their definitions.

### CODE REVIEW

**Comment by eldargab** [comment]
Ok, thank you. I'll make a release soon and will mention you here afterwards.

**Comment by eldargab** [comment]
Hi, @nikeee! It wasn't as soon as promised :), but a version which  includes types is now on npm.

**Comment by nikeee** [comment]
Finally, thanks! :)

**Comment by nikeee** [comment]
Removed from DT via https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56291

**Pull request merged**
